name: CI

on: 
  push:
    branches: 
      - dev
      - '*/dev'
  pull_request:
    branches:
      - dev
      - '*/dev'

jobs:
  build_debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: == Pre-Build ==
      run: |
        chmod -R a+x .github/CI
        [ -f .github/CI/pre-build.sh ] && .github/CI/pre-build.sh
    - name: == Build Debug ==
      run: .github/CI/build-config.sh Debug
