name: CI_dev

on:
  push:
    branches: 
      - dev
      - '*/dev'
  pull_request:
    branches:
      - dev
      - '*/dev'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: == Pre-Build ==
      run: |
        chmod a+x .github/CI/*.sh
        [ -f .github/CI/pre-build.sh ] && .github/CI/pre-build.sh TRUE
    - name: == Build Release (clang) ==
      run: .github/CI/build-config.sh Release TRUE
    - name: == Build Debug (clang) ==
      run: .github/CI/build-config.sh Debug TRUE
