name: CI

on: 
  push:
    branches:
      - master
      - '*hotfix*'
  pull_request:
    branches:
      - master

jobs:
  build_release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: == Pre-Build ==
      run: |
        chmod a+x .github/CI/*.sh
        [ -f .github/CI/pre-build.sh ] && .github/CI/pre-build.sh TRUE
    - name: == Build Release (clang) ==
      run: .github/CI/build-config.sh Release TRUE
